---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    url: "sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
  messaging:
    services:
      - name: "messaging"
        kind: "enterprise-messaging"
